/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ESCLATE_USAGE_FAULT

extern void initialise_monitor_handles();
extern void init_all_fault_handlers();
extern void enable_exception_zerodivide();

// Usage Fault demo
void induce_usagefault_undefinedinst()
{
	typedef void (*fun)(void);

	fun fun1 = (fun)0x20000201; // undefined instr...

	fun1();
}

int fun_div(int a, int b)
{
	return a / b;
}

// Demo Divide by zero, usage fault
void induce_usagefault_zerodiv()
{
	int div = fun_div(15, 0); // trapped by usage fault, div by zero trap enabled
}

void induce_busfault_InvalidMemoryAddrAccess()
{
	volatile int *invalid_address = (int *)0xFFFFFFFF;

	// Attempt to write to the invalid address
	*invalid_address = 0xDEADBEEF;
}

void induce_memoryfault_ExecXNregion()
{
	// 0x40000000-0x5FFFFFFF :Peripheral Device XN region
	typedef void (*fun)(void);

	fun fun1 = (fun)(0x40000000U | 0x1U);

	fun1();
}
#define CASE 4

int main(void)
{

	initialise_monitor_handles();
	// #define ESCLATE_USAGE_FAULT, enable in fault.c to see escalation for usage fault
	init_all_fault_handlers();

	enable_exception_zerodivide();

#if CASE == 1

	induce_usagefault_undefinedinst();

#elif CASE == 2

	induce_usagefault_zerodiv();

#elif CASE == 3

	induce_busfault_InvalidMemoryAddrAccess();

#elif CASE == 4

	induce_memoryfault_ExecXNregion();

#endif
	/* Loop forever */
	for (;;)
		;
}
