/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

__attribute__((naked)) void SVC_Handler(void)
{

	__asm volatile("MRS R0, MSP");
	__asm volatile("B SVC_Handler_c");
	__asm volatile ("BX LR");
}

void SVC_Handler_c(uint32_t *pStackBase)
{
	// Fetch the PC
	uint32_t prev_pc = (uint32_t)pStackBase[6];

	// The SVC call has SVC number
	// i.e. PC is next instr of SVC call
	// The SVC number is part of insruction / opcode
	// therefore, PC addr - 2, would contain SVC number
	uint8_t *svc_num = (uint8_t *)(prev_pc - 2);

	// to return a value, we must pass the return value via stack
	// MSP[0] -> R0, this is return register as per AAPCS, so set the
	// return value to MSP[0], which will be popped to R0 during return.
	pStackBase[0] = (uint32_t)*svc_num + 4;
}

extern void initialise_monitor_handles();

int main(void)
{

	initialise_monitor_handles();
	uint32_t ret_val = 0;
	__asm volatile("SVC #255");

#if 0
	register uint32_t svc_ret __asm("r0");
#endif

	__asm volatile("MOV %[out], R0" : [out] "=r"(ret_val));

	printf("SVC return value =%d\n", ret_val);
	/* Loop forever */
	for (;;)
		;
}
