/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ALIAS_BASE 			(0x22000000U)
#define TARGET_ADDR 		(0x20000200U)
#define TARGET_BASE_ADDR 	(0x20000000U)
#define TARGET_BIT 			(9U)

#define ALIAS_ADDR ((ALIAS_BASE) + (32 * (TARGET_ADDR - TARGET_BASE_ADDR)) + (4 * TARGET_BIT))

int main(void)
{

	initialise_monitor_handles();
	// Toggle the TARGET_BIT at TARGET_ADDR

	uint8_t *val = ((uint8_t *)(TARGET_ADDR));
	// toggle the TARGET_BIT (garbage value)
	*val ^= (1 << TARGET_BIT);

	// now let us toggle with bit banding

	uint8_t *bit_band_val = ((uint8_t *)(ALIAS_ADDR));

	*bit_band_val = !(*bit_band_val);

	/* Loop forever */
	for (;;)
		;
}
